[workspace]
resolver = "3"
members = [
    "pictogram",
    "pictogram-core",
    "pictogram-dioxus",
    "pictogram-icons-bootstrap",
    "pictogram-icons-feather",
    "pictogram-icons-font-awesome",
    "pictogram-icons-hero",
    "pictogram-icons-ion",
    "pictogram-icons-lucide",
    "pictogram-icons-oct",
    "xtask",
]
