[workspace]
resolver = "3"
members = [
    "pictogram",
    "pictogram-core",
    "pictogram-dioxus",
    "pictogram-icons-bootstrap",
    "pictogram-icons-feather",
    "pictogram-icons-font-awesome",
    "pictogram-icons-hero",
    "pictogram-icons-iconoir",
    "pictogram-icons-ion",
    "pictogram-icons-lobe",
    "pictogram-icons-lucide",
    "pictogram-icons-material",
    "pictogram-icons-oct",
    "pictogram-icons-phosphor",
    "pictogram-icons-simple",
    "pictogram-icons-tabler",
    "pictogram-icons-vscode",
    "xtask",
]
