[package]
name = "pictogram"
version = "0.3.0"
edition = "2024"
authors = ["Tom Dymel <tom@dymel.dev>"]
readme = "../README.md"
repository = "https://github.com/tdymel/pictogram"
documentation = "https://docs.rs/pictogram"
license = "MIT OR Apache-2.0"
description = "A compile time svg icon catalogue."
keywords = ["icons", "svg", "dioxus", "leptos"]
categories = ["gui", "web-programming", "accessibility", "wasm"]
exclude = ["tests"]

[dependencies]
pictogram-core = { path = "../pictogram-core", version = "0.3.0" }
pictogram-icons-lucide = { path = "../pictogram-icons-lucide", version = "0.3.0", optional = true }
pictogram-icons-bootstrap = { path = "../pictogram-icons-bootstrap", version = "0.3.0", optional = true }
pictogram-icons-feather = { path = "../pictogram-icons-feather", version = "0.3.0", optional = true }
pictogram-icons-font-awesome = { path = "../pictogram-icons-font-awesome", version = "0.3.0", optional = true }
pictogram-icons-hero = { path = "../pictogram-icons-hero", version = "0.3.0", optional = true }
pictogram-icons-ion = { path = "../pictogram-icons-ion", version = "0.3.0", optional = true }
pictogram-icons-oct = { path = "../pictogram-icons-oct", version = "0.3.0", optional = true }

[features]
default = ["bootstrap", "feather", "font-awesome", "hero", "ion", "lucide", "oct"]
lucide = ["dep:pictogram-icons-lucide"]
bootstrap = ["dep:pictogram-icons-bootstrap"]
feather = ["dep:pictogram-icons-feather"]
font-awesome = ["dep:pictogram-icons-font-awesome"]
hero = ["dep:pictogram-icons-hero"]
ion = ["dep:pictogram-icons-ion"]
oct = ["dep:pictogram-icons-oct"]
