[package]
name = "pictogram-icons-oct"
version = "0.4.0"
edition = "2024"
authors = ["Tom Dymel <tom@dymel.dev>"]
readme = "README.md"
repository = "https://github.com/tdymel/pictogram"
documentation = "https://docs.rs/pictogram"
license = "MIT OR Apache-2.0"
description = "Primer Octicons export for pictogram"
keywords = ["icons", "svg", "dioxus", "leptos", "primer-octicons"]
categories = ["gui", "web-programming", "accessibility", "wasm"]

[dependencies]
pictogram-core = { path = "../pictogram-core", version = "0.4.0" }

# Read and written by `cargo xtask update oct`.
[package.metadata.pictogram]
upstream = "https://github.com/primer/octicons"
upstream-version = "19.33.0"
